### ISSUE TITLE
API documentation inaccurate

### ISSUE THREAD

**Issue by ponasromas** [paysera/lib-webtopay#5]
https://developers.paysera.com/lt/checkout/integrations/integration-library

There is example with callback.php where method "checkResponse" is used. Which is deprecated in favor of "validateAndParseData". Kindly please invest 2 minutes and update your documentation to reflect newest changes to the library.

**Comment by pelanis** [comment]
It's resolved, documentation updated.

The main issue with validateAndParseData is that those who just copy/paste code are not implementing the check for status = 1, that's why we kept the deprecated method in there.
